# Generated by Django 5.0 on 2026-02-13 22:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Remera Oversize Negra, Buzo con Capucha, Gorra TINCHO', max_length=200, verbose_name='Nombre del Producto')),
                ('talle', models.CharField(choices=[('S', 'Small (S)'), ('M', 'Medium (M)'), ('L', 'Large (L)'), ('XL', 'Extra Large (XL)'), ('XXL', 'Double XL (XXL)')], help_text='Talle del producto', max_length=3, verbose_name='Talle')),
                ('precio_costo', models.DecimalField(decimal_places=2, help_text='Cuánto nos costó el producto', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio de Costo')),
                ('precio_venta', models.DecimalField(decimal_places=2, help_text='Precio al que se vende al cliente', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio de Venta')),
                ('stock_actual', models.IntegerField(default=0, help_text='Cantidad disponible en inventario', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Actual')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional del producto', null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Si el producto está disponible para la venta', verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre', 'talle'],
                'indexes': [models.Index(fields=['nombre'], name='inventario__nombre_2dddb1_idx'), models.Index(fields=['is_active', 'stock_actual'], name='inventario__is_acti_d0ff41_idx')],
                'unique_together': {('nombre', 'talle')},
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Venta')),
                ('cantidad', models.IntegerField(help_text='Cantidad de unidades vendidas', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio por unidad al momento de la venta', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio Unitario')),
                ('total', models.DecimalField(decimal_places=2, editable=False, help_text='Total de la venta (se calcula automáticamente)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Total')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta')], default='EFECTIVO', max_length=20, verbose_name='Método de Pago')),
                ('notas', models.TextField(blank=True, help_text='Observaciones adicionales sobre la venta', null=True, verbose_name='Notas')),
                ('vendedor', models.CharField(blank=True, help_text='Quién realizó la venta (opcional)', max_length=100, null=True, verbose_name='Vendedor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='inventario.producto', verbose_name='Producto Vendido')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='inventario__fecha_957dbb_idx'), models.Index(fields=['producto', '-fecha'], name='inventario__product_7b215a_idx')],
            },
        ),
    ]
