# Generated by Django 5.0 on 2026-02-18 14:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre', 'variante'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, help_text='Opcional. Ej: "Ropa", "Capilar", "Accesorios"', max_length=100, null=True, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='producto',
            name='variante',
            field=models.CharField(blank=True, help_text='Opcional. Ej: "S", "250ml", "Azul", "1kg"', max_length=50, null=True, verbose_name='Variante'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(help_text='Ej: Shampoo Keratina, Remera Oversize, Pomada Mate', max_length=200, verbose_name='Nombre del Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, help_text='Cuánto costó el producto', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio de Costo'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria'], name='inventario__categor_7227b5_idx'),
        ),
        migrations.RemoveField(
            model_name='producto',
            name='talle',
        ),
    ]
