# Generated by Django 5.0 on 2026-02-10 14:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barbero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='barberos/', verbose_name='Foto de perfil')),
                ('telefono', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="El teléfono debe tener el formato: '+999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcar para ocultar al barbero sin eliminar su historial', verbose_name='Activo')),
                ('color_hex', models.CharField(default='#3B82F6', help_text='Color en formato hexadecimal (ej: #3B82F6) para diferenciar turnos en calendario', max_length=7, verbose_name='Color identificativo')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso')),
            ],
            options={
                'verbose_name': 'Barbero',
                'verbose_name_plural': 'Barberos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del servicio')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio ($)')),
                ('duracion_minutos', models.PositiveIntegerField(help_text='Tiempo estimado del servicio en minutos', verbose_name='Duración (minutos)')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcar para ocultar el servicio sin eliminarlo', verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del turno')),
                ('hora', models.TimeField(verbose_name='Hora del turno')),
                ('cliente_nombre', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('cliente_telefono', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="El teléfono debe tener el formato: '+999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono del cliente')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('REALIZADO', 'Realizado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('barbero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='turnos.barbero', verbose_name='Barbero asignado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='turnos.servicio', verbose_name='Servicio solicitado')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['-fecha', '-hora'],
                'indexes': [models.Index(fields=['fecha', 'barbero'], name='turnos_turn_fecha_8eb48b_idx'), models.Index(fields=['estado'], name='turnos_turn_estado_3fab1e_idx')],
                'unique_together': {('fecha', 'hora', 'barbero')},
            },
        ),
    ]
