# Generated by Django 5.0 on 2026-02-10 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la semana')),
                ('hora_inicio', models.TimeField(help_text='Hora en que comienza a atender', verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(help_text='Hora en que termina de atender', verbose_name='Hora de fin')),
                ('descanso_inicio', models.TimeField(blank=True, help_text='Opcional: Hora de inicio del almuerzo/descanso', null=True, verbose_name='Inicio de descanso')),
                ('descanso_fin', models.TimeField(blank=True, help_text='Opcional: Hora de fin del almuerzo/descanso', null=True, verbose_name='Fin de descanso')),
                ('barbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='turnos.barbero', verbose_name='Barbero')),
            ],
            options={
                'verbose_name': 'Horario de atención',
                'verbose_name_plural': 'Horarios de atención',
                'ordering': ['barbero', 'dia_semana', 'hora_inicio'],
                'indexes': [models.Index(fields=['barbero', 'dia_semana'], name='turnos_hora_barbero_8505ea_idx')],
                'unique_together': {('barbero', 'dia_semana')},
            },
        ),
    ]
