# Generated by Django 5.0 on 2026-02-14 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_horarioatencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos_servicio', to='turnos.servicio', verbose_name='Servicio solicitado'),
        ),
    ]
