# Generated by Django 5.0 on 2026-02-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_alter_turno_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbero',
            name='especialidad',
            field=models.CharField(blank=True, default='', help_text='Especialidad o descripción del barbero (ej: Cortes clásicos, Barbas, etc.)', max_length=100, verbose_name='Especialidad'),
        ),
    ]
