# Generated by Django 5.0 on 2026-02-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_horarioatencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbero',
            name='is_owner',
            field=models.BooleanField(default=False, help_text='Marcar si este barbero es el dueño del negocio (recibe 100% de sus cortes)', verbose_name='Es el dueño'),
        ),
    ]
