# Generated by Django 5.0 on 2026-02-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0005_barbero_is_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbero',
            name='porcentaje_casa',
            field=models.DecimalField(decimal_places=2, default=40.0, help_text='Porcentaje que se queda la casa por cada corte (ej: 40.00 significa 40%)', max_digits=5, verbose_name='Porcentaje para la Casa (%)'),
        ),
    ]
