# Generated by Django 5.0 on 2026-02-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0006_barbero_porcentaje_casa'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta')], max_length=20, null=True, verbose_name='Método de pago'),
        ),
    ]
