# Generated by Django 5.0 on 2026-02-18 22:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0007_add_metodo_pago_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbero',
            name='telefono',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="El teléfono debe tener el formato: '+999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono'),
        ),
    ]
