# Generated by Django 5.0 on 2026-02-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0008_alter_barbero_telefono'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'PENDIENTE')), fields=('fecha', 'hora', 'barbero'), name='unique_turno_pendiente'),
        ),
    ]
